### ISSUE TITLE
谷歌浏览器53版本，一些小问题

### ISSUE THREAD

**Issue by zhaoweihan** [baijunjie/jQuery-photoClip#10]
用谷歌浏览器53版本，此插件在调出file控件的文件选取器时会非常慢，大概需要3-4秒左右。（其他浏览器并无此问题，谷歌其他版本没测，但也应该没有这个问题）

**Comment by zhaoweihan** [comment]
原因找到了  在给file 控件元素添加 accept 属性时，属性值设置成了image/_（源码中这样写的$file.attr("accept", "image/_") 102行）。应该把image/\*  改为"image/png, image/jpeg" 。具体原因还在调查，但w3shool 上面建议 并不要用这个属性！

**Comment by baijunjie** [comment]
感谢反馈
