### ISSUE TITLE
您好，这边有一个问题，想请教一下您：当选取的图片的宽度大于高度时，图片不能完全暴露在裁剪框中。ios：可以各方面旋转，即使旋转到一个角度，暴露了整张图片在裁剪框，也会有留白部分，感觉不是很好看。android：为了性能，默认不能自由旋转，图片不能完全暴露在裁剪框中。请问，有什么办法能使宽大于高的图片完全暴露在裁剪框中，并且裁剪出来的图片没有留白透明部分呢。

### ISSUE THREAD

**Issue by jojo-1995** [baijunjie/jQuery-photoClip#100]
- 如果遇到使用问题，可以使用我提供的 Demo 进行问题重现，首先排除自己编码导致的问题。
- 如果遇到兼容问题，请先自己 debug 定位出问题，并将问题的详细描述、使用设备的型号、版本等尽量详细的信息提供给我。
- 如果你能亲自解决问题，并修复代码，欢迎 pull requests。

**Comment by baijunjie** [comment]
图片在裁剪框中的显示策略类似于 `background-position: cover`，原因是为了确保图片裁剪完成后，能够得到一张没有空白边缘的图片，起到强制用户提交符合业务需求比例图片的目的。

如果需要使图片完全暴露在裁剪框中，那么图片裁剪的意义似乎就失去了，唯一做到的或许仅仅是图片压缩，这样的话，也就没有使用图片裁剪插件的理由了。
