### ISSUE TITLE
demo outputSize: [0, 0] 选择图片就报错了

### ISSUE THREAD

**Issue by medwinwang** [baijunjie/jQuery-photoClip#11]

**Comment by baijunjie** [comment]
请先确认demo不是在本地环境下运行的，因为本地环境下chrome会有跨域报错

**Comment by medwinwang** [comment]
应该不是，本地起了个nginx服务的

**Comment by baijunjie** [comment]
错误信息贴出来看一下

**Comment by medwinwang** [comment]
![qq 20160718142333](https://cloud.githubusercontent.com/assets/6041034/16907141/62d6d974-4cf3-11e6-9712-e6b59e7ce1d6.png)

**Comment by baijunjie** [comment]
把错误日志展开，看一下是哪一行代码报错。另外问一下，是否试过不同的图片？还是说只试了一张图片？我这里确实没有报错
