### ISSUE TITLE
图片压缩lrz(file, [options])的options参数没写——[lrz.all.bundle.js] 插件

### ISSUE THREAD

**Issue by thxl2010** [baijunjie/jQuery-photoClip#12]
图片压缩**jquery.photoClip.js**的_L115_ `lrz`方法忽略了压缩参数（[文档](https://github.com/think2011/localResizeIMG/wiki/2.-%E5%8F%82%E6%95%B0%E6%96%87%E6%A1%A3)），所以图片还是原来的尺寸。上传图片过大时，缩放会卡。

**Comment by baijunjie** [comment]
感谢，新版本已经增加了对应的配置参数
