### ISSUE TITLE
用微信自带的选照片功能，选完照片后，用jQuery-photoClip截图，clipFinish函数一直没执行。

### ISSUE THREAD

**Issue by oscar608** [baijunjie/jQuery-photoClip#13]

**Comment by baijunjie** [comment]
您的问题描述太模糊了

**Comment by momosc** [comment]
我也遇到这个问题  在微信里  clipFinish     data: {str: dataURL} 返回的图片base64地址有问题，我的其他图片都可以上传，微信二维码传不了！！！！       pc端 和移动端浏览器打开都可以上传所有图片（包括微信二维码）
