### ISSUE TITLE
希望支持size: ['100%', '100%']百分比

### ISSUE THREAD

**Issue by chenchuxin** [baijunjie/jQuery-photoClip#14]
![image](https://cloud.githubusercontent.com/assets/16110593/17588449/91b4bda8-6001-11e6-9c0e-77ec7a8889b3.png)
我写了size: ['100%', '100%']是上面这样~

**Comment by baijunjie** [comment]
这个参数不支持百分比，只能使用具体像素值

**Comment by chenchuxin** [comment]
所以跪求添加百分比!

**Comment by baijunjie** [comment]
去更新 1.10.1版本吧

**Comment by chenchuxin** [comment]
谢谢老板
