### ISSUE TITLE
长方形的图片不能把整个图片截取进去，能根据图片宽高自动控制截取框吗

### ISSUE THREAD

**Issue by medwinwang** [baijunjie/jQuery-photoClip#15]

**Comment by baijunjie** [comment]
额，根据图片宽高等比例截取？那截图插件的意义是什么？如果只是需求压缩图片的话，你可以直接使用图片压缩插件。

**Comment by medwinwang** [comment]
就是长方形的图片没法整个放到截取框了，有个图案是长的话 没法整个截取出来

**Comment by baijunjie** [comment]
尝试一下最新版的 setSize()，可以手动更改截取框的大小

**Comment by medwinwang** [comment]
setTimeout(function(){
        clipArea.setSize(174, 260);  
    },1000);
![qq 20160816161824](https://cloud.githubusercontent.com/assets/6041034/17692590/08a1f4de-63cd-11e6-84f6-f78e29267e37.png)

缩小不行了

**Comment by baijunjie** [comment]
什么意思？

**Comment by medwinwang** [comment]
延迟执行 setSize  会有点问题，图片会右移动，缩小也缩不到最小

**Comment by baijunjie** [comment]
好的，v2.0.1修复了这个问题。
