### ISSUE TITLE
裁减出来的图片为什么比源图容量大3倍  以上

### ISSUE THREAD

**Issue by eallern** [baijunjie/jQuery-photoClip#17]
原图是 40k左右的大小，经过裁减后，变成了220多k。 @baijunjie  请问这个问题怎么解决呢？

**Comment by baijunjie** [comment]
裁剪的图片像素尺寸是多大？裁剪后的像素尺寸是否比原图要大？

**Comment by eallern** [comment]
可打开此图片作为一个对比。或者你可以自己测试下。
图片地址：
http://res2.playwx.com/wechat/app/201608/18094822_g0VT.jpg

**Comment by baijunjie** [comment]
这个插件只是帮助你来裁剪图片尺寸，对于手机中过大的照片会有一定的压缩功能。但不能保证裁剪出来的图片就一定会比原图小。这是canvas的绘图API的问题，我无能为力。

**Comment by baijunjie** [comment]
我在v2.0.2中加入了outputQuality参数，用来控制canvas输出质量。但是仍然不能保证最终输出的图片一定会比原图小。希望对你有帮助。
