### ISSUE TITLE
微信里用这个插件传不了微信二维码，非二维码图片都可以上传！

### ISSUE THREAD

**Issue by momosc** [baijunjie/jQuery-photoClip#18]
遇这个问题 在微信里 clipFinish data: {str: dataURL} 返回的微信二维码图片base64地址有问题微信二维码传不了！！！！ 

pc端 和移动端浏览器打开都可以上传所有图片（包括微信二维码）！

**Comment by baijunjie** [comment]
能否把微信中截图的返回结果打印出来发给我看一下

**Comment by momosc** [comment]
微信客户端 没办法看到输出结果  ，微信开发调试工具也是正常的，不过在网上别的地儿下了你这个插件在微信端就可以了，我自己还在对比中。。。  文件比最新版少了个lrz.all.bundle.js       jquery是2.13的 别的都一样     photoClip v1.5.1版本的ok   莫非lrz.all.bundle.js 压缩二维码图片后微信浏览器不识别了

**Comment by momosc** [comment]
下了版本测试  1.10.0以上的不行  往下就测试了v1.9.1 可以的 

v1.10.0 增加了 [lrz.all.bundle.js] 插件（文档）的配置参数，如果加载完图片后出现卡顿或崩溃现象，可以尝试设置此参数。 就是这个东西  不知道怎么解决 研究中

**Comment by momosc** [comment]
先用v1.9.1了

**Comment by baijunjie** [comment]
最好能先用alert排除一下故障点。因为之前是直接将file中的图片进行裁剪，iphone上会有问题，比如照片的方向不正确。后来使用lrz，才解决了这个问题。这个插件对手机照片提取的兼容性做的比较好。

**Comment by Dengjiansheng** [comment]
那有没有可能就是微信本身的权限问题，对于二维码，不允许进行上传

**Comment by Dengjiansheng** [comment]
测试二维码图片生成的base64正常识别，微信二维码是啥意思
