### ISSUE TITLE
大神好，插件好喜欢，只是想请教一下这个插件怎么跟webuploader配合使用啊

### ISSUE THREAD

**Issue by jiadaoyun** [baijunjie/jQuery-photoClip#19]
如题，话说我给你发过红包哈，问题解决后还会发的大大的红包呢

**Comment by jiadaoyun** [comment]
我纠结的是webuploader需要入口，PhotoClip也需要入口，怎么解决这个先后的问题啊

**Comment by baijunjie** [comment]
你说的入口指的是什么？

**Comment by jiadaoyun** [comment]
入口就是点击上传的那个按钮啊

**Comment by baijunjie** [comment]
PhotoClip 没有点击上传的按钮， 只有从相册选取照面的所谓“上传按钮”，和裁图确认按钮

**Comment by jiadaoyun** [comment]
就是这个相册选取按钮，回到最开始的问题吧，怎么跟webuploader使用啊。大神肯定知道webuploader的

**Comment by baijunjie** [comment]
请描述清楚你的需求。你想实现什么功能，你用了webuploader什么功能，又用photoclip什么功能，都帮你实现了那部分功能，具体卡在那一步？是什么问题？瓶颈在哪里？我只能帮你解决具体的问题

**Comment by jiadaoyun** [comment]
大神好，我现在用的是webuploader的上传功能。有一个上传按钮，点一下然后图片上传到服务器。
现在想加入裁剪功能，希望是在图片上传之前把图片裁剪一下，所以找到了您的photoclip。
现在问题是，如果使用photoclip的选择图片按钮，图片可以裁剪出来，生成一个图片的base64，我怎么才能继续使用webuploader里面把图片上传上去呢

**Comment by baijunjie** [comment]
那么这个问题其实和 photoclip 无关，这个要看webuploader的上传机制了，看看它有没有提供非file来源的图片上传的API，我也不是很了解。
