### ISSUE TITLE
有计划不依赖jquery吗

### ISSUE THREAD

**Issue by acitydu** [baijunjie/jQuery-photoClip#20]
作者做的插件非常好，经常在项目中使用，非常感谢。
不过最近开始使用vue后不再引入jquery了，也不想再专门为了一个插件专门引入jquery。
不知道作者有没有计划去掉jquery的依赖？

**Comment by baijunjie** [comment]
目前没有这个计划。我也在用vue，而 jquery 只是一个DOM操作的工具集，两者并不冲突。况且总是要有一个工具来完成DOM操作工作的，不用 jquery 就的用其他工具库，我更倾向于使用前者。

**Comment by baijunjie** [comment]
v3.0.0 已经移除了对 jQuery 的依赖
