### ISSUE TITLE
请问这是什么原因？

### ISSUE THREAD

**Issue by gotoin** [baijunjie/jQuery-photoClip#21]
require加载 
PhotoClip.js?v=201601250001:247 Uncaught TypeError: IScroll is not a constructor

**Comment by gotoin** [comment]
自己解决了 IScroll-zoom.js最底下改成 

`if (typeof define == 'function' && define.amd) {
    define(function() {
        return IScroll;
    });
} else if ( typeof module != 'undefined' && module.exports ) {
    module.exports = IScroll;
} else {
    window.IScroll = IScroll;
}`

**Comment by baijunjie** [comment]
``` js
require.config({
    paths: {
        'iscroll': 'iscroll-zoom',
    },
    shim: {
        'iscroll': {
            exports: 'IScroll'
        }
    }
});
```
