### ISSUE TITLE
大神好，lrzOption好像不起作用，压缩不了图片大小

### ISSUE THREAD

**Issue by chris926** [baijunjie/jQuery-photoClip#24]
最终上传的照片很大，导致ios崩溃，android没问题
lrzOption具体这个如何使用呢，能不能压缩尺寸或像素呢

**Comment by baijunjie** [comment]
https://github.com/think2011/localResizeIMG/wiki/2.-%E5%8F%82%E6%95%B0%E6%96%87%E6%A1%A3

lrzOption是根据这个文档来设置的，至于压缩后的质量问题，我也并不清楚。

你也可以直接设置一下 outputQuality，这个压缩我使用的是 canvas.toDataURL(outputType, outputQuality); 希望能有些效果吧。

**Comment by chris926** [comment]
嗯，其实我提这个问题是因为ios下总是闪退，所以想尝试压缩，android没有问题，是上传的问题吗

**Comment by chris926** [comment]
能否详细说明一下参数 adaptive，outputSize，特别是adaptive的用法

**Comment by baijunjie** [comment]
adaptive:['80%','80%']   这个你用demo自己设置一下就知道了

outputSize意思就是输出图片的像素宽高

**Comment by chris926** [comment]
解决了，原来是js版本没搞对，谢谢！
