### ISSUE TITLE
extend有bug，把dom元素copy成普通对象了，而且会死循环。

### ISSUE THREAD

**Issue by wmlgl** [baijunjie/jQuery-photoClip#26]
另外， iscroll5.2配置里zoomStart变成startZoom了。
图片缩小到一定程度后会隐藏，放大后会显示。
Android5.1，微信最新版, qq和uc不会。

**Comment by baijunjie** [comment]
感谢指出，目前3.0.1，已经修复了extend的问题。
startZoom 也修改了过来，不过这个并不会对程序有影响。
至于Android 5.1的问题，手头上没有测试设备，无法测试。如果可以的话，希望能帮我找到问题点。

**Comment by baijunjie** [comment]
已经更新 v3.0.2，具体改动可以查看 changelog
