### ISSUE TITLE
在移动端的体验很不好，缩放的时候会旋转导致图片可能会消失不见

### ISSUE THREAD

**Issue by slmev** [baijunjie/jQuery-photoClip#27]
![image](https://cloud.githubusercontent.com/assets/18041237/21518169/6190e13e-cd1f-11e6-8dd0-58d9dddfb6db.png)
就这种情况，突然就不见了

**Comment by baijunjie** [comment]
是安卓系统吗？能否说明下具体怎么操作后出现这种情况？

**Comment by slmev** [comment]
是安卓系统，还会出现这种情况
![image](https://cloud.githubusercontent.com/assets/18041237/21518271/427bf6d4-cd20-11e6-815f-9f10c31d53e8.png)
就随便缩放，旋转就会造成这种情况

**Comment by baijunjie** [comment]
提供一下你安卓的机型和系统版本

**Comment by slmev** [comment]
华为Mate 9 Android 7.0

**Comment by baijunjie** [comment]
我测试了下，的确在有的安卓机上有严重的性能问题，主要原因可能是自由旋转引起的，导致页面不断重绘，压力很大，我现在还没有好的解决方案，目前只能是先禁止掉安卓机上的自由旋转。你可以先加下我的QQ，我给你发一个测试版，实验一下。

**Comment by baijunjie** [comment]
我测试了下，的确在有的安卓机上有严重的性能问题，主要原因可能是自由旋转引起的，导致页面不断重绘，压力很大，我现在还没有好的解决方案，目前只能是先禁止掉安卓机上的自由旋转。

**Comment by yunuo-tech** [comment]
我也碰到找个情况了 ，无论安卓还是 iphone 都有这问题

**Comment by yunuo-tech** [comment]
@baijunjie 你好 请问你是怎么禁止自由旋转的

**Comment by baijunjie** [comment]
已经更新 v3.0.2，具体改动可以查看 [changelog](https://github.com/baijunjie/PhotoClip.js/blob/master/Changelog.md)
