### ISSUE TITLE
怎么在vue-cli项目中使用啊？

### ISSUE THREAD

**Issue by zwellgood** [baijunjie/jQuery-photoClip#28]
import IScroll from '../assets/js/iscroll-zoom'
import Hammer from '../assets/js/hammer.min'
import lrz from '../assets/js/lrz.all.bundle'
import PhotoClip from '../assets/js/PhotoClip'

这样直接import 会报错。。。
ERROR in ./src/assets/js/PhotoClip.js
Module not found: Error: Cannot resolve module 'iscroll-zoom' in /home/zz/Desktop/vue-wechat/src/assets/js
 @ ./src/assets/js/PhotoClip.js 13:2-52

ERROR in ./src/assets/js/PhotoClip.js
Module not found: Error: Cannot resolve module 'hammer' in /home/zz/Desktop/vue-wechat/src/assets/js
 @ ./src/assets/js/PhotoClip.js 13:2-52

ERROR in ./src/assets/js/PhotoClip.js
Module not found: Error: Cannot resolve module 'lrz' in /home/zz/Desktop/vue-wechat/src/assets/js
 @ ./src/assets/js/PhotoClip.js 13:2-52

**Comment by baijunjie** [comment]
AMD或者CommonJS规范的模块在不依赖其他模块的情况下，可以使用ES6的import导入，例如：jQuery。
但是如果有依赖其他模块，就不能使用import了。
```js
        if (typeof define === 'function' && define.amd) {
		define(['iscroll-zoom', 'hammer', 'lrz'], factory);
	} else if (typeof exports === 'object') {
		module.exports = factory(require('iscroll-zoom'), require('hammer'), require('lrz'));
	} else {
		root.PhotoClip = factory(root.IScroll, root.Hammer, root.lrz);
	}
```
PhotoClip 使用的是UMD写法，在ES6中会跳过 amd 判定，直接使用 module.exports，但是问题在于ES6无法获取 require('iscroll-zoom') 和 require('hammer') 的模块，因为他无法识别这两个模块名。
你可以尝试将这两个模块名修改为文件路径，如果不行的话，只能使用<script>正常导入了。

**Comment by baijunjie** [comment]
AMD或者CommonJS规范的模块在不依赖其他模块的情况下，可以使用ES6的import导入，例如：jQuery。
原因是 Vue-cli 中好像可以兼容这两种规范的写法。
但是如果有依赖其他模块，就不能直接使用import了。
```js
if (typeof define === 'function' && define.amd) {
	define(['iscroll-zoom', 'hammer', 'lrz'], factory);
} else if (typeof exports === 'object') {
	module.exports = factory(require('iscroll-zoom'), require('hammer'), require('lrz'));
} else {
	root.PhotoClip = factory(root.IScroll, root.Hammer, root.lrz);
}
```
PhotoClip 使用的是UMD写法，问题在于 Vue-cli 无法识别 define(['iscroll-zoom', 'hammer', 'lrz'], factory) 中声明的依赖模块，因为它没有 require.config 来预先定义模块名以及关联的文件路径。因此需要针对 Vue-cli 环境修改代码。
假设你的文件目录在 js/PhotoClip/ 下，你可以将这一段修改为以下形式：
```js
if (typeof define === 'function' && define.amd) {
	define([
		'../../js/PhotoClip/iscroll-zoom',
		'../../js/PhotoClip/hammer.min',
		'../../js/PhotoClip/lrz.all.bundle'
	], factory);
} else if (typeof exports === 'object') {
	module.exports = factory(
		require('../../js/PhotoClip/iscroll-zoom'),
		require('../../js/PhotoClip/hammer.min'),
		require('../../js/PhotoClip/lrz.all.bundle')
	);
} else {
	root.PhotoClip = factory(root.IScroll, root.Hammer, root.lrz);
}
```
亲测，可行。

**Comment by zwellgood** [comment]
恩恩   修改了没报错  请教一下new PhotoClip('#clipArea');这个应该加在哪里。。。
<template>
    <div class="_full_inner _effect component-camera" :class="{'_effect--30':decline}">
        <article class="zzsc-container">
            <div id="clipArea"></div>
            <a class="upfile" href="javascript:;">
              <input type="file" id="file" draggable="false" single accept="image/jpg,image/jpeg,image/png,image/gif"/>
            </a>
            <button id="clipBtn">确定</button>
        </article>
    </div>
    <router-view transition="cover"></router-view>
</template>


<script>
import IScroll from '../assets/js/iscroll-zoom'
import Hammer from '../assets/js/hammer.min'
import lrz from '../assets/js/lrz.all.bundle'
import PhotoClip from '../assets/js/PhotoClip'
export default {
      data() {
              return {
                  decline: false
                  new PhotoClip('#clipArea');
              }

          },
        events: {
            'route-pipe' (_decline) {
                this.decline = _decline
                this.$parent.$emit('route-pipe', _decline)
            }
        }
}
</script>

**Comment by zwellgood** [comment]
恩恩  修改了 没报错   还想请教一下new PhotoClip('#clipArea'); 应该加在哪里。。。
``<template>
    <div class="_full_inner _effect component-camera" :class="{'_effect--30':decline}">
        <article class="zzsc-container">
            <div id="clipArea"></div>
            <a class="upfile" href="javascript:;">
              <input type="file" id="file" draggable="false" single accept="image/jpg,image/jpeg,image/png,image/gif"/>
            </a>
            <button id="clipBtn">确定</button>
        </article>
    </div>
    <router-view transition="cover"></router-view>
</template>
<script>
import IScroll from '../assets/js/iscroll-zoom'
import Hammer from '../assets/js/hammer.min'
import lrz from '../assets/js/lrz.all.bundle'
import PhotoClip from '../assets/js/PhotoClip'
export default {
      data() {
              return {
                  decline: false
                  new PhotoClip('#clipArea');
              }

          },
        events: {
            'route-pipe' (_decline) {
                this.decline = _decline
                this.$parent.$emit('route-pipe', _decline)
            }
        }
}
</script>

**Comment by baijunjie** [comment]
目前已经可以直接在 vue-cli 中引入使用，无需修改代码。
唯一要注意的是 .babelrc 文件的配置，需要开启支持 ES5 模块。
```json
{
  "presets": [
    "env",
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```
