### ISSUE TITLE
一点小建议。

### ISSUE THREAD

**Issue by huajilancey** [baijunjie/jQuery-photoClip#3]
近来因为弄个微信页面需要用到上传头像的功能，无意中发现了这个小插件，用起来感觉挺好的。但有个小问题，我看了下注释，相信作者也发现了，就是ios照片的方向问题。其实这个问题可以通过Exif.js来解决，具体见 http://code.ciaoca.com/javascript/exif-js/ ，可以在图片转base64编码后，检测Orientation值来判断图片方向，在初始化时把图片旋转到正确的方向。希望这点建议对插件的改进会有帮助。

**Comment by baijunjie** [comment]
感谢您的建议，以及给到的解决方案。只是由于工作原因，很长一段时间没有维护代码了，如果您愿意的话，可以直接提交版本，我来合并进来。如果实在没有时间的话，我之后会找时间进行改进。再次感谢！

**Comment by baijunjie** [comment]
v1.6.0中已经将该问题解决
