### ISSUE TITLE
安卓设备上options.img属性设置的问题

### ISSUE THREAD

**Issue by yafanzhang** [baijunjie/jQuery-photoClip#30]
在安卓设备上使用此插件，options.img属性设置为file:///data/data/com.abc.cheng/cache/tmp_ImageSelector_20161121_121131-751232154.JPEG,无法正常运行，这个问题怎么解决？

**Comment by baijunjie** [comment]
你可以先使用
```html
<img src="file:///data/data/com.abc.cheng/cache/tmp_ImageSelector_20161121_121131-751232154.JPEG">
```
来测试你的设备是否可以从这个路径中正确获取图片
options.img 也是这样获取的

**Comment by wmlgl** [comment]
可以把图片转成data uri
