### ISSUE TITLE
希望大神能添加圆形截图功能

### ISSUE THREAD

**Issue by auven** [baijunjie/jQuery-photoClip#31]

**Comment by baijunjie** [comment]
其实我很好奇，什么样的需求非要圆形图片才可以实现？

**Comment by auven** [comment]
我现在遇到一个需求，就是要抠出人脸，然后p到另外一张图上，所以如果可以有圆形或者是椭圆最好。

**Comment by baijunjie** [comment]
嗯，这个需求我需要好好构思一下，裁成圆形或者椭圆很简单，但是有一点是如何实现一个镂空的圆形或椭圆遮罩？还要保证能适配不同尺寸，和浏览器兼容性。如果你有很好的思路不妨提出来？

**Comment by huangzizhao** [comment]
你好，因为实际需求，有个建议在这里提一下，比如我想在移动端截取正方形图片，截图框能设置成宽度为当前设手机的宽度，高度和前面的宽度一样（PS：虽然这样会在pc端表现会很奇怪），作者觉得这个想法怎么样，有没有可能实现

**Comment by baijunjie** [comment]
仔细阅读下文档的 `options.adaptive`  选项，似乎可以满足你的需求

**Comment by zhe-he** [comment]
我画了个简单的图，如图：
![111](https://cloud.githubusercontent.com/assets/11306583/24028230/4bfce04e-0b08-11e7-8b50-d9b4d6ef879c.jpg)
我们知道要截取圆的半径R，可以用 getImageData 获取此片区域的像素集合。
H是通过循环  image高度 j 来知道，
难点是 怎么通过H 和 R 来算出下面 横线X的长度，知道这个后 就好做后续的图片圆形裁剪了。

**Comment by baijunjie** [comment]
@zhe-he 你想复杂了，利用canvas API 能轻松搞定，所以截取圆形并不是问题。问题是如何制作出一个浏览器兼容性比较好的圆形遮罩，目前我能想到的只有svg

**Comment by zhe-he** [comment]
用手机端用svg会很卡，不建议使用。
刚看了下你的蒙层，给个建议,蒙层可以如下修改：
蒙层改为一体（现在是分成上下左右4个）, 中间亮的部分改为真实图片的 部分区域（现在是 一个透明的正方形）， 拖动图片时改变 蒙层中图片的 位置和大小。

**Comment by baijunjie** [comment]
@zhe-he 这的确是一个思路，不过这需要创建两个照片元素，在移动端的性能消耗太高，尤其是内存占用会很大，因为一张照片在有些设备上都已经造成应用崩溃了，所以照片加载时不得不进行一次压缩。
