### ISSUE TITLE
希望添加下载图片功能

### ISSUE THREAD

**Issue by auven** [baijunjie/jQuery-photoClip#32]
目前我知道保存图片的方式有一下几种：
1.将canvas转base64放入img标签里，长按保存图片，但是有些浏览器兼容性不是很好。
2.js创建a标签，将href替换为base64数据，并添加download属性，兼容性也不是很好，电脑上可以下载，手机上有些浏览器没反应，有些是跳转页面展示图片。

找来找去找不到很好的解决办法，所以希望大神能出个方案，适应不同设备、不同浏览器的图片下载方案！

**Comment by baijunjie** [comment]
这个需求需要后端来完成，前端无解
