### ISSUE TITLE
安卓手机调出的图片选择界面在“最近图片“文件中选的图片无法显示

### ISSUE THREAD

**Issue by xiongxliu** [baijunjie/jQuery-photoClip#35]
安卓手机调出的图片选择界面在“最近图片“文件中选的图片无法显示，只能在相册里面的图片才能显示。能否直接调用的是“照片”里面的图片？想微信的图片上传一样，直接进入的是“图片”。

**Comment by baijunjie** [comment]
估计和安卓系统对file控件的支持有关，你可以测试一下其他的网页上传是否也无法使用“最近图片“来确定这个问题。目前来看，前端没有什么很好的解决方案。

**Comment by baijunjie** [comment]
你可以尝试修改源码的654行，将file控件的accept属性赋值注释掉，看看是否还存在这儿问题。

```js
// 移动端如果设置 'accept'，会使相册打开缓慢，因此这里只为非移动端设置
if (!is_mobile) {
    attr(this._$file, 'accept', 'image/jpeg, image/x-png, image/gif');
}
```
