### ISSUE TITLE
图片截取后有很多小白点

### ISSUE THREAD

**Issue by David-Pan** [baijunjie/jQuery-photoClip#36]
图片压缩失真太严重了，导致图片有很多白点，请问有什么解决方法吗？
`outputQuality: 1,
        lrzOption: {
            quality: 1
        },`这里我改到最高了

**Comment by baijunjie** [comment]
是否所有照片都是如此？我这里并没有发现会失真到如此严重的程度。这里的质量实际上就是`canvas.toDataURL()`中的质量参数。
另外，`lrzOption.width`, `lrzOption.height` 也会影响你的图片质量，在安卓设备上，为了防止页面卡顿，会将宽高默认限制在1000，源码如下：
```js
lrzOption: {
   width: is_android ? 1000 : undefined,
   height: is_android ? 1000 : undefined,
   quality: .7
}
```
你可以尝试将配置项改回undefined，然后观察一下是否还会有严重的失真，不过这可能导致页面卡顿严重。

**Comment by David-Pan** [comment]
嗯，我试过很多图片都这样。我只在PC端使用该插件。如果我把outputsize改成450，小白点就不会特别明显，如果低于450就失真太严重了。

**Comment by baijunjie** [comment]
这个问题应该是图片本身过大，当缩放到一个非常小的比例时，就会出现严重失真。

**Comment by baijunjie** [comment]
因为`lrzOption.width`, `lrzOption.height`在PC上是不限制宽高的，照片原图一般会非常大，直接缩放过小就会失真，你可以尝试修改一个合适的宽高，看看是否能解决这个问题。
