### ISSUE TITLE
为什么我截取完成后图片模糊不清楚，请问该如何解决

### ISSUE THREAD

**Issue by TOUGHOU** [baijunjie/jQuery-photoClip#38]
我已经把outputQuality设置为1，而且lrzOption的quality设置为1，为什么还是有点模糊。如何禁用压缩，或者检测图片大于一个值得时候才启用压缩。

**Comment by baijunjie** [comment]
https://github.com/baijunjie/PhotoClip.js/issues/36 这个问题应该和你的差不多
