### ISSUE TITLE
ios系统上渲染不出图片

### ISSUE THREAD

**Issue by lllianreg** [baijunjie/jQuery-photoClip#43]
拍照后上传图片不显示，点击裁剪按钮会提示没有可裁剪图片  切换用uc浏览器也不行

<img width="375" alt="_20170704182006" src="https://user-images.githubusercontent.com/21689406/27826419-7aabca76-60e5-11e7-86ea-663ae6670e0c.png">

**Comment by lllianreg** [comment]
安卓手机就没问题

**Comment by baijunjie** [comment]
抱歉，兼容性问题的话，需要你自己先通过debug定位出问题，我们再想解决方案。
