### ISSUE TITLE
iscroll在安卓7.0（Chrome 55以后）下以后会出现滚动卡顿的问题

### ISSUE THREAD

**Issue by cjbi** [baijunjie/jQuery-photoClip#45]
我是按照这里面的方法解决的:
https://github.com/cubiq/iscroll/issues/1100
修改了PhotoClip.js的源代码
![image](https://user-images.githubusercontent.com/15916978/28001861-b262bc46-6562-11e7-95cf-b91cdf57674c.png)

希望作者可以适配下安卓7.0

**Comment by baijunjie** [comment]
感谢，当我确认这个改动不会有其他副作用后，就会进行更新。

**Comment by cathy-zhao** [comment]
使用这种方式，在 Android 上的卡顿问题确实解决了。但是，又引起了新的问题：列表里的点击事件却失效了
