### ISSUE TITLE
ios或安卓裁剪图片时，如果图片太大经常会出现图片是旋转90度的状态。

### ISSUE THREAD

**Issue by tuiqu** [baijunjie/jQuery-photoClip#52]
这种情况并不是必现，同一张图片偶尔出现，基本是大图出现，这是内存不足吗？

**Comment by baijunjie** [comment]
读取图片后，图片是旋转90度呈现的吗?

不太确定原因，插件依赖 [localResizeIMG](https://github.com/think2011/localResizeIMG) 这个库来读取压缩图片的，而这个库使用了  [Exif](https://github.com/exif-js/exif-js) 来判断照片方向，可能是什么原因导致判断失误吧
