### ISSUE TITLE
ios或者安卓载入拍摄的竖图时会旋转

### ISSUE THREAD

**Issue by lxlyjss** [baijunjie/jQuery-photoClip#53]
我测试了ios系统和安卓系统微信浏览器中,载入拍摄的竖图时会旋转,横着拍的图片不会旋转,程序是否有判断当图片的高度大于宽度时会旋转?但是载入普通图片,也是竖图时又不会旋转,请问这是什么问题呢?谢谢

**Comment by baijunjie** [comment]
参考这里的回答
https://github.com/baijunjie/PhotoClip.js/issues/52

**Comment by lxlyjss** [comment]
不好意思,我下载的不是最新版本,新版本已经解决这个问题了,谢谢

**Comment by baijunjie** [comment]
好的
