### ISSUE TITLE
你好，我想问一下为什么我用load()文件对象  不报错  也没有图片

### ISSUE THREAD

**Issue by phpgiter** [baijunjie/jQuery-photoClip#55]
如题   因为我用的是html5+api使用拍照返回文件对象，然后用load不显示图片，也没有进到loadStart函数里，百思不得解，请教你一下，十分感谢。

**Comment by baijunjie** [comment]
请先确保 load 方法中传入的是文件对象，通常是 files[0]
建议直接在源码中debug
