### ISSUE TITLE
拼接的div直接会出现间隔，导致出现白线，如下图

### ISSUE THREAD

**Issue by slmev** [baijunjie/jQuery-photoClip#57]
移动端出现的，chrome模拟的也会出现
![image](https://user-images.githubusercontent.com/18041237/33870118-573a9d98-df47-11e7-87d0-104a54d6020e.png)

**Comment by baijunjie** [comment]
似乎某些浏览器里会这样，主要原因可能是浏览器支持像素后的小数点的位数不同，导致的计算误差。
我很好奇你是怎么实现圆形遮罩的？并且你的圆形看起来很奇怪，好像有点变形？

**Comment by slmev** [comment]
![image](https://user-images.githubusercontent.com/18041237/33870634-b8c95610-df49-11e7-81cd-2ea414e86bcd.png)
demo在chrome模拟的iphone 6 plus会出现白线，本来就是不规则的圆，用的背景图

**Comment by baijunjie** [comment]
chrome 上应该是因为你的游览器被缩放了  不是100%

**Comment by slmev** [comment]
好像是的，那应该是我这边的问题。。。谢谢了
