### ISSUE TITLE
希望有销毁函数

### ISSUE THREAD

**Issue by GuoDapeng** [baijunjie/jQuery-photoClip#6]
原因是这样的，当开发 Web APP 时，看似不同的页面确实在一个 html 里，有不同尺寸的图片需要上传时，我们向复用一个页面时变得困难。

希望添加一个这样的函数。^_^

**Comment by baijunjie** [comment]
Please use the 1.8.0 comes with

**Comment by baijunjie** [comment]
使用1.8.0版本吧
