### ISSUE TITLE
请问下，如何调整 图片放大或缩小的速率

### ISSUE THREAD

**Issue by jasonyqwang** [baijunjie/jQuery-photoClip#60]
请问下，如何调整 图片放大或缩小的速率：
问题场景：
上传一张像素很大的图片，使用鼠标滑动截图的时候，要滑动好多次。
有没有可以设置滑动速率的参数

**Comment by baijunjie** [comment]
缩放速率是在 iscroll-zoom.js 中写死的，目前没有可配置的参数，需要修改的话可以下载源码进行修改
https://github.com/baijunjie/iscroll 这里是我的Fork，修复了一些原来的 bug，你可以参考 `修改说明.md` 进行修改。

**Comment by jasonyqwang** [comment]
好的，谢谢
