### ISSUE TITLE
clip circle picture

### ISSUE THREAD

**Issue by RrtoyewxXu** [baijunjie/jQuery-photoClip#62]
如果截取一张圆角或者圆形图片，大佬能不能扩展下 plz

**Comment by baijunjie** [comment]
实在需要截取圆形的话可以自己修改最终的输出方法来实现，canvas截取圆形还是比较简单的

只是目前没有想到能够实现黑色圆形遮罩的方法，所以这个功能一直没有添加，如果有好的实现方法可以告诉(*￣︶￣)
