### ISSUE TITLE
初始化加载js文件报错,

### ISSUE THREAD

**Issue by rhfij** [baijunjie/jQuery-photoClip#64]
PhotoClip.min.js:2 js  文件报错
Uncaught TypeError:     t is not a constructor
    at e.C._initScroll (PhotoClip.min.js:2)
    at e.C._init (PhotoClip.min.js:2)
    at new e (PhotoClip.min.js:2)
    at createClip (poster_template.html:343)
    at poster_template.html:395
看到麻烦回复一下,谢谢啦~~~

**Comment by baijunjie** [comment]
如果不是使用不当的话，应该不会有这个问题。

可以先使用 PhotoClip.js 看看哪有有错，如果只是 PhotoClip.min.js 的问题，请重新 build 后再尝试。

**Comment by rhfij** [comment]
我没有使用build，我是直接加载那几个js文件的，所以一直找不到原因在哪里




| |
wxy
邮箱：weixinyue9999@163.com
|

签名由 网易邮箱大师 定制

在2018年02月07日 12:38，白俊杰 写道：

如果不是使用不当的话，应该不会有这个问题。

可以先使用 PhotoClip.js 看看哪有有错，如果只是 PhotoClip.min.js 的问题，请重新 build 后再尝试。

**Comment by baijunjie** [comment]
如果没有使用模块加载器，那么 PhotoClip 就不能单独使用，必须先引入依赖的 js 插件， 请参照demo的使用方式。

**Comment by rhfij** [comment]
加载了依赖的js的，详情看附件




| |
wxy
邮箱：weixinyue9999@163.com
|

签名由 网易邮箱大师 定制

在2018年02月08日 14:53，白俊杰 写道：

如果没有使用模块加载器，那么 PhotoClip 就不能单独使用，必须先引入依赖的 js 插件， 请参照demo的使用方式。
