### ISSUE TITLE
Android下小米max有多处出边。

### ISSUE THREAD

**Issue by LiuDuFenLi** [baijunjie/jQuery-photoClip#65]
[https://img.115.com/thumb/P/BJ/0F/PBJ0F80581FDFC1661F2E3457490C05E009_800_800?s=t2bAtIBrYJQJneI_gAUVgw&t=1519636874&sync=1](url)

**Comment by baijunjie** [comment]
看不到你的图

**Comment by baijunjie** [comment]
如果有新的反馈，请重新打开
