### ISSUE TITLE
有没有设置PhotoClip对象outputSize的属性？

### ISSUE THREAD

**Issue by bozomoyy** [baijunjie/jQuery-photoClip#67]
文档是有pc.size(width, height);这个设置pc对象的截取框宽高的方法，但是有没有设置outputSize的值的呢（需求需要）？

**Comment by baijunjie** [comment]
抱歉，目前没有这个实例方法，如果需要变更 outputSize，需要销毁原对象并重新创建对象。

之前并没有考虑到，需要在不销毁原对象的情况下，连续输出多种不同尺寸的图片的可能。

因为这并不属于前端的刚性需求，由于前端上传数据应遵循尽量精简的原则，所以生成不同尺寸的任务应该交由后端的图片处理引擎来处理。

size的设计思路只是为了让开发者控制用户提交图片的宽高比例，及原图质量。

**Comment by baijunjie** [comment]
如果有新的反馈，请重新打开
