### ISSUE TITLE
苹果手机无法缩放图片，且会消失

### ISSUE THREAD

**Issue by ztpark** [baijunjie/jQuery-photoClip#68]
测试机：IPone5，IPone6S，IPone7
选择图片后，图片很大，只显示了其中最左上角的一角。
双指捏合，图片会动一下，但手指放掉，里面又恢复原样，且一不小心图片就飞掉了，消失了。
![tim 20180315160950](https://user-images.githubusercontent.com/22342802/37451171-b4d9592c-286b-11e8-8d8a-2ed61f97e0a0.png)
![tim 20180315161000](https://user-images.githubusercontent.com/22342802/37451172-b6b6c8f6-286b-11e8-8411-7b6387159bf5.png)

另外：在 android 4 的手机中测试，无法缩放和旋转。android 5和6中是正常可以使用的。

附上我的代码（因为初始图片是跨站加载，所以重写了初始加载图片的方法）：
![hhtzec t1i da x nucqvn](https://user-images.githubusercontent.com/22342802/37451568-e09ed856-286c-11e8-9533-692bba838160.png)

**Comment by baijunjie** [comment]
HI, @Spmr03 首先不要随意修改插件生成的DOM元素，这会使插件内部的对象引用以及一些绑定事件丢失。

如果图片加载出来后，首先呈现的不是图片中心，而是左上角的话，那一定是初始化程序出现了错误，要找到使它出错的原因。

希望先运行我提供的demo进行客户端测试，排除掉开发代码中可能出现的使用不当的问题，尽可能的缩小问题排查范围。

**Comment by ztpark** [comment]
多谢楼主的提醒。现在不修改插件生成的DOM元素，采用其他方式加载初始图片，可以用了。
