### ISSUE TITLE
new多个photoClip(),如果输入框 获得焦点后，其它photoClip，会错位

### ISSUE THREAD

**Issue by yaoyuande** [baijunjie/jQuery-photoClip#69]
1.  # bug
     new 多个photoClip对象（需要并存，不能销毁），如果有input或者textarea 获得焦点后，当前photoClip正常，其它的photoClip位置自动 跳到左上角了

2. #  步骤
    进入页面需要初始化三个photoClip,一屏显示一个，可以左右切换photoClip，进行操作，最张点击生成，截出 3个 图，提交后台

3. #  期望
  输入文字后，其它photoClip,不能错位

**Comment by yaoyuande** [comment]
在pc端没问题，在移动端会出现此问题。安卓 苹果都有

**Comment by baijunjie** [comment]
photoClip 的父级元素是否使用了 `position: fixed` ?
据我所知，移动端浏览器在输入状态时，fixed的元素会有错位问题。
希望可以提供一个重现问题的测试demo，方便我进一步测试问题所在。

**Comment by yaoyuande** [comment]
这个是我的项目地址：https://running.osports.cn/biqu/page/expression/index.html#/ExpressionMany

只在当前页显示一个Input，就能发现这个问题。

父级没有 position: fixed;
源码都能看得到

期待大神的回复

**Comment by baijunjie** [comment]
我用手机测试了你的demo，没有出现你所说的问题
测试设备是 iphone6p

你的设备是 iOS 还是 Android?

如果是 Android 设备，估计问题就很难解决了。

**Comment by yaoyuande** [comment]
刚才 又重新试了下。苹果5会有问题。安卓设备也会有问题。这个怎么办呢？

**Comment by yaoyuande** [comment]
大神你这么厉害，相信你肯定可以的

**Comment by baijunjie** [comment]
这种问题只能设法规避，你可以尝试将其他photoclip的 `display: none` 移除，使用其他的隐藏手段(不会影响自身的宽高)，比如设置 `left: 100%`, 父容器 `overflow: hidden`

**Comment by yaoyuande** [comment]
好的。我试试。多谢指导了

**Comment by yaoyuande** [comment]
@baijunjie  你说的方案 完美解决了我的问题了。多谢指导。 再次感谢大神帮忙
