### ISSUE TITLE
不能连续上传同一张本地图片进行裁剪

### ISSUE THREAD

**Issue by xingorg1** [baijunjie/jQuery-photoClip#73]
操作描述：
点击选择图片，选择一张本地图片A，截取A图后，选择确认上传生成base64码，然后关掉裁剪弹窗。清空div#clipArea内部的结构并调用clipArea.destroy();销毁实例。
再次点击选择本地同一张图片A，此时调出的截取框空白无图，点击确认上传提示没有选择图片，观察没有走到loadStart这个回调中
但是如果换一张B图片上传完毕后，再选择A图就可以了。
请问大家有遇到过么，什么原因啊实在是找不出来。

**Comment by xingorg1** [comment]
观察感觉好像是input type=file那里，没有清除上一次选择的图片
后来发现真的是，因为第一次上传后input file的value值没有被清空，里边还是上一次的路径，所以再次选择同一张图片，路径没有变化就没有触发change事件，所以就没有什么反应，后边的一系列现象也就容易解释了。

最后解决方法（本人本次，如果大神有好方法感谢指导）
在done的回调里边，把input那个结构的value值设为空的字符串了：$('#file').val('');
另外为了防止万一，我在图片加载失败等回调中也设置了一下。

**Comment by baijunjie** [comment]
谢谢，我在 v3.3.9 中修复了这个问题

**Comment by xingorg1** [comment]
感谢大神指导，我这就换成3.3.9的试试。还想请问下是什么原因导致的呢？是因为input type=file的值没清空的原因吗？

**Comment by xingorg1** [comment]
另外，这个问题我用input type值清空的方法，大部分浏览器都好了，但是ie10还是存在这个问题

**Comment by baijunjie** [comment]
@xingorg1 应该是值未被清空的问题，或许ie10中直接给`file.vaue`赋一个空值不能够清空它，如果你能找出原因或者是清空值的方法请告诉我，如果无法解决，可以尝试在销毁插件后重新创建一个`file`替换掉它

**Comment by xingorg1** [comment]
在ie10中我尝试了一下，确实是file还存在路径。很有可能是这个原因，我这就试试你说的方法。谢谢

**Comment by xingorg1** [comment]
ie10中问题解决了：确实重新创建了一个file替换掉原来的就可以了：
网上找的一段原生js替换input元素的方法，解决了问题。感谢感谢！！
function clearFile() {
        var oldFile = document.getElementById('file');
        var newFile = document.createElement('input');
        newFile.id = oldFile.id;
        newFile.type = 'file';
        newFile.accept = 'image/jpeg, image/x-png, image/gif';
        oldFile.parentNode.replaceChild(newFile, oldFile);
    }
