### ISSUE TITLE
正常上传图片可以destroy()销毁实例，点击取消或close，销毁实例不起作用

### ISSUE THREAD

**Issue by xingorg1** [baijunjie/jQuery-photoClip#74]
1.按照正常流程，成功上传完图片后销毁实例是没有问题
2.如果裁好了图片点击取消按钮或者close，而不是点击确认上传，执行销毁实例
3.再次上传，如果不选图直接点击确认上传会弹窗两次提示
再次执行一遍2-3，则弹窗提示累加一次

大致代码如下，请问怎么解决呢？
let clipArea = new photoClip()
done: (dataURL)=> {clipArea.destroy();}
取消按钮.click => clipArea.destroy();
关闭按钮.click => clipArea.destroy();

**Comment by baijunjie** [comment]
可能是在没有成功销毁插件的同时，又一次new的插件导致的多次事件绑定

**Comment by xingorg1** [comment]
使用clipArea.destroy()应该可以销毁插件的啊，确认上传就能成功销毁，但是取消上传和close时，使用clipArea.destroy()就没有起作用。

**Comment by baijunjie** [comment]
我不清楚以前的版本是否有这个 bug，目前最新版应该不会出现此类问题了，如果仍有问题，请从新打开这个issue
