### ISSUE TITLE
ie10,11的一些问题

### ISSUE THREAD

**Issue by xingorg1** [baijunjie/jQuery-photoClip#75]
ie10,11中不能使用url上传图片，chrome可以（这个不知道是不是因为测试用的ie是在虚拟机中的原因，但是控制台也没有提示跨域）。
ie10,11中上传本地图片过大会崩溃，但是同样的尺寸图在chrome中可以。

大神们有遇到同样的问题的么，能指导一下怎么解决么

写了这么多，感觉好内疚啊，这么看来测试也不是一个轻松的活了。
接下来我找到解决方法会记录在这里。

**Comment by baijunjie** [comment]
其实我也缺少这方面的测试和解决方案，希望能够提供更多的帮助来改进插件

**Comment by baijunjie** [comment]
如果有新的反馈，请重新打开
