### ISSUE TITLE
如果图片跨域了怎么alert用户提示

### ISSUE THREAD

**Issue by xingorg1** [baijunjie/jQuery-photoClip#76]
在photoclip中有很丰富的错误提示，现在遇到一个跨域后没有办法提示用户的难题。

**Comment by baijunjie** [comment]
其实关于跨域错误主要是给开发人员看的，用户并不能理解它的意思，用户上传图片时不应该发生跨域的错误。开发人员应该避免让用户输入其他域的图片链接地址的方式上传图片。

**Comment by baijunjie** [comment]
如果实在是需要将错误抛出给用户，可以修改 `options.errorMsg.clipError` 为一个错误码，然后在 `options.fail` 的回调中比对错误参数是否为这个错误码，最后用自己想要的方式给用户提示
