### ISSUE TITLE
vue项目使用，报These dependencies were not found

### ISSUE THREAD

**Issue by silence1996** [baijunjie/jQuery-photoClip#78]
您好，我在vue项目里想引入您的插件，npm后import PhotoClip from 'photoclip'却报了以下错误

* utils/$ in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/attr in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/bind in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/createElement in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/css in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/destroy in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/extend in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/hideAction in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js, ./node_modules/_photoclip@3.4.0@photoclip/src/utils.js
* utils/isArray in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/isNumber in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js
* utils/removeElement in ./node_modules/_photoclip@3.4.0@photoclip/src/index.js

To install them, you can run: npm install --save utils/$ utils/attr utils/bind utils/createElement utils/css utils/destroy utils/extend utils/hideAction utils/isArray utils/isNumber utils/removeElement

**Comment by baijunjie** [comment]
抱歉，由于换了新的构建工具，导致这个问题，你可以暂时暂时安装以前的版本，明天我会对应这个问题

**Comment by silence1996** [comment]
谢谢， 请问该改为哪个版本

**Comment by baijunjie** [comment]
我发布了新的版本 v3.4.2，你可以尝试一下
