### ISSUE TITLE
安装3.4.2版本报错

### ISSUE THREAD

**Issue by xingorg1** [baijunjie/jQuery-photoClip#79]
大神，我们的脚手架依赖您的photoclip插件，配置里写的3.3.6版本的，但是今天一安装自动安装3.4.2的，且报错，然后我单独安装，一样的报错。
cnpm i --S photoclip@3.4.2
\ [0/1] Installing photoclip@3.4.2[photoclip@3.4.2 › iscroll@github:baijunjie/iscroll] install iscroll from git github:baijunjie/iscroll, may be very slow, please keep patience
× Install fail! Error: [photoclip@3.4.2 › @module-factory/utils@0.1.5] Can't find package @module-factory/utils's version: 0.1.5
Error: [photoclip@3.4.2 › @module-factory/utils@0.1.5] Can't find package @module-factory/utils's version: 0.1.5
    at resolve (C:\Users\g\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:96:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\g\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npminstall version: 3.7.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\g\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\guojufeng1\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org --S photoclip@3.4.2

然后我用npm安装也不行
npm i --S photoclip@3.4.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @module-factory/utils@0.1.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'photoclip'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\g\AppData\Roaming\npm-cache\_logs\2018-06-28T07_20_49_714Z-debug.log

这是啥原因啊，我看npm官网上是有3.4.2的啊

**Comment by baijunjie** [comment]
非常抱歉，之前的版本被我废除了，请重新跟新到 3.4.3

另外我看到你使用的是淘宝镜像，可能会有些延迟

**Comment by xingorg1** [comment]
恩，好的。非常感谢 。我先试试
