### ISSUE TITLE
"^3.3.8" 每次初始化成功都会执行一次fail，clear()清除的时候mask仍然存在

### ISSUE THREAD

**Issue by haoyinag** [baijunjie/jQuery-photoClip#80]
如题：
比如我利用弹窗初始化，总共初始化了10次，无论我裁剪确定还是取消，都会累加一次fail对象，我在done的时候已经clear了，不是应该不会有10次吗？

另外，我是用弹窗实现的初始化，然后把图片内容换成文字内容的时候，图片的遮罩层还存在，即会把我重新生成的弹窗的文字盖住。

**Comment by baijunjie** [comment]
更新到最新版后，看看还会不会有这个问题

**Comment by haoyinag** [comment]
@baijunjie 可以了
