### ISSUE TITLE
安卓微信端无法运行

### ISSUE THREAD

**Issue by oakelk** [baijunjie/jQuery-photoClip#81]
微信公众号开发，首先编码肯定没有问题，ios微信、安卓外置浏览器 都可以选择图片并编辑。但是微信内置浏览器，选择图片后没有反应，多个安卓手机都是这样。

**Comment by oakelk** [comment]
demo在安卓微信端也不行

**Comment by baijunjie** [comment]
@oakelk 或许是安卓端微信浏览器内核更新后导致的不兼容，我目前没有测试条件，如果可以的话，希望能帮助我在该环境下找到具体是哪里不能正常工作。例如报错代码位置，或者是代码由于某种原因没能执行等。

**Comment by baijunjie** [comment]
如果有新的反馈，请重新打开
