### ISSUE TITLE
npm run build fail

### ISSUE THREAD

**Issue by Nikkolast88** [baijunjie/jQuery-photoClip#82]
import PhotoClip from 'photoclip'
In the component
ERROR in static/js/0.63ba58c2baddca0446cd.js from UglifyJs
Unexpected token name «p», expected punc «;» [static/js/0.63ba58c2baddca0446cd.js:27,17]

  Build failed with errors.

**Comment by sRoke** [comment]
me too

**Comment by baijunjie** [comment]
@DengRiGuang  Vue cli ?
I failed to reproduce your question. Can you provide more information about your configuration?
