### ISSUE TITLE
紧急！版本3.4.3及以下，IOS10.3及以下报错！

### ISSUE THREAD

**Issue by haoyinag** [baijunjie/jQuery-photoClip#83]
如题，该问题只在IOS10.3以下会有问题，也许是ES6的问题，也许哪里处理有问题，导致页面整个加载失败；
初步估计是可能有ES6的代码导致的
项目要上线了，紧急处理啊大哥！！！
（如果方便加下微信不：haoyinag）

**Comment by baijunjie** [comment]
用v3.4.4

**Comment by haoyinag** [comment]
@baijunjie 最新版的还是3.4.3

**Comment by haoyinag** [comment]
npm install 的版本还是3.4.3呢，
如果引入四个js的话：
1、import './PhotoClip/PhotoClip.js'; 这样引入报错 PhotoClip is not defined
2、如果这样引入import PhotoClip from './PhotoClip/PhotoClip.js'; 报错 "export 'default' (imported as 'PhotoClip') was not found in './PhotoClip/PhotoClip.js'

**Comment by baijunjie** [comment]
抱歉，我的疏忽，新版本并没有发布，晚些我会重新发布

**Comment by haoyinag** [comment]
好的。感谢!

**Comment by baijunjie** [comment]
@haoyinag 发布了，你试试吧

**Comment by haoyinag** [comment]
更新3.4.4了，还是不能兼容，不知道问题出现在哪里；
另外，一个jq项目用的也是你的插件，但没有问题 ，是不是打包的时候哪里处理不一样或是别的什么原因呢

**Comment by baijunjie** [comment]
package.json
```
...
  "main": "dist/PhotoClip.js",
  "module": "src/index.js",
...
```
也就是说，如果你的项目使用的是 ES6 开发，那么这个模块会以ES6模块的方式被导入，这就要求你必须在 babel-loader 的设置中 include `node_modules`, 否则 `node_modules` 中所有的 ES6 模块都无法被正确编译。我猜测是这个问题

或者你可以直接使用 dist 中的 `PhotoClip.js` 
```
import PhotoClip from 'photoclip/dist/PhotoClip.js'
```

**Comment by haoyinag** [comment]
`include: [resolve('src'),resolve('node_modules/photoclip'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]`
这样处理我是不是include错了，不行。但是
`import PhotoClip from 'photoclip/dist/PhotoClip.js'`这样是可以的。
总之现在问题终于解决了，真的是非常感谢！！！

@baijunjie Then:现在是本地能正常运行，打包到线上后又不行了，这是不是还有哪里没处理到 T_T

**Comment by baijunjie** [comment]
@haoyinag 线上报错是什么？

**Comment by haoyinag** [comment]
@baijunjie 又没问题了。不知道是不是昨天忘记清缓存了 |@_@|

so，感谢之余总感觉以后还是会有别的问题麻烦你~

**Comment by baijunjie** [comment]
@haoyinag 没关系，有问题可以继续提issue，但是这个插件有一些固有的兼容bug，目前无法fix，此外的一些问题我会抽时间对应

**Comment by haoyinag** [comment]
额额~感谢！
另外有些问题想请教下：

1.     我现在公司的项目是老大5年前用jquery用几个月写出来的项目，由于已经上线且用户较多，当时很多东西没考虑，导致现在维护及其困难。然后想用vue重构，但代价太大公司不同意 ，我该怎么劝说呢！？或者还有没有必要继续留下来呢，因为我感觉在这首先没技术好的人带领，啥事都是自己摸索，我是从培训机构出来的，只有高中毕业，很多东西感觉学的吃力，虽然我热爱这个行业，但总感觉力不从心；其次项目一直用这jq维护迭代，感觉自己都要跟前端时代脱节了。

2.    然后我一直想给自己做个职业计划，就是先把前端的一些基本栈学好了，或者能够独立做项目，然后找空学另外一门语言golang或者pythen，觉得这个计划可行吗。行业的说法是35岁之后就不敲代码了，而我已经29岁了，刚入行一年，有点迷茫。请问我这个计划可行不，或者有没有好点的建议呢~？

3.    最后是想问下，因为公司项目和人员搭配的关系，前端的工程化技术栈用不上，也没有人带领，然后我到现在为止连webpack都用不好，我该怎么去定个计划来提高自己的技术呢；像你这个插件的很多写法我都看不大懂。

――――如有空，希望不吝指教下，感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 白俊杰 <notifications@github.com>
发送时间: Monday, August 13, 2018 10:22:05 AM
收件人: baijunjie/PhotoClip.js
抄送: Chen; Mention
主题: Re: [baijunjie/PhotoClip.js] 紧急！版本3.4.3及以下，IOS10.3及以下报错！ (#83)


@haoyinag<https://github.com/haoyinag> 没关系，有问题可以继续提issue，但是这个插件有一些固有的兼容bug，目前无法fix，此外的一些问题我会抽时间对应

―

**Comment by baijunjie** [comment]
好吧，我大概说一下我的想法：

首先，我要纠正一个错误观点，35岁之后不敲代码，不是说就不写代码了，而是很多细枝末节的具体代码你不需要亲手去实现了，要么安排给其他level比较低程序员来做，要么就是利用好现成的第三方工具，年龄不是问题，问题在于你是否能帮助公司解决实际问题，如果只是完成上面安排下来的 coding 任务，那35岁之后的确是没有竞争力了。

实际上，技术是为业务来服务的，如果业务上没有需要，或者并没有因为技术上的落后遇到不可解决的问题，完全没有必要去使用新技术重构（当然，除非公司目前就这一个项目，并且你很闲）。再加上前端代码重构的意义本身就不大。而是应该想一下怎么样使用新技术去创建目前公司需要且没有的新项目，在新项目中去实践，一个项目的好坏其实更重要的是后端的架构。

如果你目前的工作就只是负责维护这个项目的话，你可以尝试用业余时间来进行重构，然后将测试通过的成品直接拿给上司看。google 很多大型项目都是这样完成重构的。公司要考虑成本和风险，所以不会轻易允许程序员利用工作时间来重构项目。

全栈是必须的，不论你学习哪一种后端语言，最终目标是能够了解一个应用从后台到前台的全部实现流程，每种技术的优缺点，结合公司的应用实践，如何升级这个应用系统，让他更高效，这是最宝贵的经验。

公司永远最需求的是提供解决方案的人才，而不是完成工作的员工。因为后者很好招，还有大批的外包公司。

**Comment by haoyinag** [comment]
嗯~首先感谢回复！

1.     因为整个项目当时是前后端一起写的，所以明显后端架构也是十分糟糕，虽然如此，线上还是能勉强跑的；所以也只能按照你说的，利用业余时间一点点重构吧，也正好能更加的锻炼自己。

2.    然后这段时间公司让我领导整个前端小组，加我共4个前端，但是我才只有1年的实际经验，领导经验为零，平时一些如bug啥的不但不能帮忙解决，生产力也不及他们，毕竟他们年轻，所以我就会感觉心慌，力不从心，这个有没有好的办法~

3.    最后仍是十分感谢你的意见，起码给了我方向感以及你宝贵的经验。

――十分感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 白俊杰 <notifications@github.com>
发送时间: Monday, August 13, 2018 3:00:47 PM
收件人: baijunjie/PhotoClip.js
抄送: Chen; Mention
主题: Re: [baijunjie/PhotoClip.js] 紧急！版本3.4.3及以下，IOS10.3及以下报错！ (#83)


好吧，我大概说一下我的想法：

首先，我要纠正一个错误观点，35岁之后不敲代码，不是说就不写代码了，而是很多细枝末节的具体代码你不需要亲手去实现了，要么安排给其他level比较低程序员来做，要么就是利用好现成的第三方工具，年龄不是问题，问题在于你是否能帮助公司解决实际问题，如果只是完成上面安排下来的 coding 任务，那35岁之后的确是没有竞争力了。

实际上，技术是为业务来服务的，如果业务上没有需要，或者并没有因为技术上的落后遇到不可解决的问题，完全没有必要去使用新技术重构（当然，除非公司目前就这一个项目，并且你很闲）。再加上前端代码重构的意义本身就不大。而是应该想一下怎么样使用新技术去创建目前公司需要且没有的新项目，在新项目中去实践，一个项目的好坏其实更重要的是后端的架构。

如果你目前的工作就只是负责维护这个项目的话，你可以尝试用业余时间来进行重构，然后将测试通过的成品直接拿给上司看。google 很多大型项目都是这样完成重构的。公司要考虑成本和风险，所以不会轻易允许程序员利用工作时间来重构项目。

全栈是必须的，不论你学习哪一种后端语言，最终目标是能够了解一个应用从后台到前台的全部实现流程，每种技术的优缺点，结合公司的应用实践，如何升级这个应用系统，让他更高效，这是最宝贵的经验。

公司永远最需求的是提供解决方案的人才，而不是完成工作的员工。因为后者很好招，还有大批的外包公司。

―

**Comment by baijunjie** [comment]
@haoyinag 关于第二点，我也没有好的办法，我的经验是，既然由你来领导小组，那么就不要什么事都亲力亲为，把尽可能多的任务分派出去，然后集中精力去攻克难题，提升自己，这是个好机会。

有时候技术上不一定要什么都精通，如果走向管理，要学会拆解工作，把工作模块化，然后将细分的功能需求分派出去，由别人来完成，这也是我从模块化开发中学到的，希望对你有帮助。

**Comment by haoyinag** [comment]
嗯~我最近的做法就是大概这样，把项目按功能板块划分，然后分别负责各个板块，并在以后的时间里持续跟进维护。
既然和你的建议不谋而合，那么以后的新项目/任务也会按这个模式去分配了。
~再次感谢指导！

另~
鉴于我的计算机基础以及各方面知识的薄弱，我想买些书来充下电，有没有好的书籍可以推荐呢。
我现在只有js的红皮书和犀牛书（都没看 T_T），想按你说的全栈发展，然后想找些计算机基础/网络相关？的书籍，还有一些设计模式、vue相关的书籍看看，
或者认为在慕课网上的一些收费解说视频有没有去看的价值呢！？
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 白俊杰 <notifications@github.com>
发送时间: Tuesday, August 14, 2018 6:16:52 PM
收件人: baijunjie/PhotoClip.js
抄送: Chen; Mention
主题: Re: [baijunjie/PhotoClip.js] 紧急！版本3.4.3及以下，IOS10.3及以下报错！ (#83)


@haoyinag<https://github.com/haoyinag> 关于第二点，我也没有好的办法，我的经验是，既然由你来领导小组，那么就不要什么事都亲力亲为，把尽可能多的任务分派出去，然后集中精力去攻克难题，提升自己，这是个好机会。

有时候技术上不一定要什么都精通，如果走向管理，要学会拆解工作，把工作模块化，然后将细分的功能需求分派出去，由别人来完成，这也是我从模块化开发中学到的，希望对你有帮助。

―

**Comment by baijunjie** [comment]
说实话，我不怎么看书，主要是没有时间，需求太多，每天针对需求去学习就已经能学到很多了，并且现在知识更新的很快，书已经跟不上技术发展进度了。而且很多概念在你没有遇到实际需求时，是很难理解并应用的。

我建议是从自己手头的项目入手，每个环节都要对自己刨根问底，有不懂的地方直接去网上找答案，有针对性的学习。

**Comment by haoyinag** [comment]
好吧~受教了，感谢！！！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 白俊杰 <notifications@github.com>
发送时间: Friday, August 17, 2018 10:22:45 AM
收件人: baijunjie/PhotoClip.js
抄送: Chen; Mention
主题: Re: [baijunjie/PhotoClip.js] 紧急！版本3.4.3及以下，IOS10.3及以下报错！ (#83)


说实话，我不怎么看书，主要是没有时间，需求太多，每天针对需求去学习就已经能学到很多了，并且现在知识更新的很快，书已经跟不上技术发展进度了。而且很多概念在你没有遇到实际需求时，是很难理解并应用的。

我建议是从自己手头的项目入手，每个环节都要对自己刨根问底，有不懂的地方直接去网上找答案，有针对性的学习。

―
