### ISSUE TITLE
先选择图片，再出现裁剪框

### ISSUE THREAD

**Issue by Fishlz** [baijunjie/jQuery-photoClip#84]
请问您这个插件能够实现选择图片之后在出现相应的裁剪框吗？？？谢谢

**Comment by baijunjie** [comment]
如果你是需要多个不同的裁剪框的话，可以实例化多个 Photoclip 对象，并且负责图片输入的 file 控件不能重复绑定，每个 Photoclip 对象需要绑定一个自己的 input[file]

**Comment by Fishlz** [comment]
已经解决，谢谢
