### ISSUE TITLE
Can't find variable: prefix undefined

### ISSUE THREAD

**Issue by LeeDashan** [baijunjie/jQuery-photoClip#87]
在iPhone上，上传完图片后，onload方法中报错。。
但是在pc的Chrome中模拟iPhone是好的

错误信息：
ReferenceError: Can't find variable: prefix
undefined:996:84 setTransform
_resetScroll

exports
onload

设备：iPhone 5S iOS 10.3

大佬求助~

**Comment by baijunjie** [comment]
我发布了一个新版本 `v3.4.5`，增加了容错

**Comment by LeeDashan** [comment]
> 我发布了一个新版本 `v3.4.5`，增加了容错

还是报同样的错误，然后导致初始化失败，图片无法移动缩放。。。
ReferenceError: Can't find variable: prefix
undefined:1002:84 setTransform
_resetScroll

exports
onload

发现和之前issue#83一样，IOS 10.3以下版本会报错
Duplicate of #83

**Comment by baijunjie** [comment]
你可以在源码中 `src/index.js` 找到 `prefix` 变量，debug 一下看看究竟是什么原因没有找到。
