### ISSUE TITLE
元宵节快乐~之余来个bug

### ISSUE THREAD

**Issue by haoyinag** [baijunjie/jQuery-photoClip#89]
如题：缩放的时候应该是以两指间的中心点为指针的，然而
现在放大的时候以右下角为指针，收缩的时候以左上角为指针

**Comment by baijunjie** [comment]
很遗憾，我不能重现你说的问题，在我的iphone上始终是以两指中心点作为缩放原点

**Comment by haoyinag** [comment]
找不到问题所在，暂且搁下先

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 白俊杰 <notifications@github.com>
发送时间: Tuesday, February 19, 2019 9:37:24 PM
收件人: baijunjie/PhotoClip.js
抄送: ChenHaoYin; Author
主题: Re: [baijunjie/PhotoClip.js] 元宵节快乐~之余来个bug (#89)


很遗憾，我不能重现你说的问题，在我的iphone上始终是以两指中心点作为缩放原点

―

**Comment by Fishlz** [comment]
我也遇到了这个问题
