### ISSUE TITLE
为什么不能模拟 点击ok 绑定的按钮

### ISSUE THREAD

**Issue by charrysong** [baijunjie/jQuery-photoClip#92]
点击绑定的按钮是可以的。我有多个截取的，想通过模拟的时候提交。发现不能用。

**Comment by charrysong** [comment]
像这样。
$(".imglist").each(function () {
                var sid = $(this).attr("id");
                if ($("#clipArea" + sid).html() != "") {
                    console.log("#clipbtn" + sid);
                    $("#clipbtn" + sid).click();
                }
            });

**Comment by baijunjie** [comment]
你可以调用截图的实力方法，文档中有说明

**Comment by charrysong** [comment]
循环调用的，能调用?

**Comment by charrysong** [comment]
new PhotoClip(clipid, {
                    size: [300, 300],//裁剪框大小
                    outputSize: [0, 0],//打开图片大小，[0,0]表示原图大小
                    file: "#file",
                    img: img,
                    ok:"#clipbtn"+id,
                    loadStart: function () { //图片开始加载的回调函数。this 指向当前 PhotoClip 的实例对象，并将正在加载的 file 对象作为参数传入。（如果是使用非 file 的方式加载图片，则该参数为图片的 url）
                        $(clipbg).find(".loading").removeClass("hidden");
                    },
                    loadComplete: function () {//图片加载完成的回调函数。this 指向当前 PhotoClip 的实例对象，并将图片的 <img> 对象作为参数传入。
                        $(clipbg).find(".loading").addClass("hidden");
                    },
                    done: function (dataURL) { //裁剪完成的回调函数。this 指向当前 PhotoClip 的实例对象，会将裁剪出的图像数据DataURL作为参数传入。			
                        //console.log(dataURL);//dataURL裁剪后图片地址base64格式提交给后台处理
                        $("#"+id).attr("style", "background-image:url(" + dataURL + ")");
                        $(clipbg).fadeOut();
                        $(".footer").fadeOut();
                        $(".arrow").fadeOut();
                    }
                });

**Comment by charrysong** [comment]
如果有定义变量的话就可以pc.clip()。因为循环我不好定位，有多个可能同时被渲染。

**Comment by charrysong** [comment]
记录一下我是如何解决的。在方法里面添加了一个对象数组。然后通过遍历使用data[i[.clip()。最终是实现了。
