### ISSUE TITLE
建议对于不支持SVGElement的浏览器，支持下canvas裁剪

### ISSUE THREAD

**Issue by mi4tin** [baijunjie/jQuery-photoClip#98]

**Comment by mi4tin** [comment]
哦，看了下。应该iscroll-zoom.js是这个玩意用了SVGElement造成的

**Comment by baijunjie** [comment]
@mi4tin 你好，是否是因为 `SVGElement  is undefined` 造成？能否提供一下具体的报错信息？我可以针对的修改一下

**Comment by mi4tin** [comment]
ReferenceError: Can't find variable: SVGElement

**Comment by baijunjie** [comment]
你可以尝试一下 v3.4.7，我更新了 iscroll-zoom.js，看看是否解决了这个问题
